apiVersion: v1
kind: O3Rules
metadata:
  id: node-secrets-exfiltration
  title: Node.js Secrets Exfiltration Detection
  description: Detects a multi-step attack where a node process reads .env and then attempts network egress.
  category: Supply Chain Attack
  severity: critical
spec:
  severity: critical
  target:
    binary: node
  detection:
    sequence:
      steps:
        - id: read-secrets
          file:
            read:
              path: [".env"]
        - id: network-exfil
          network:
            connect:
              direction: outbound
              scope: external
              action: block
