name: Kayo Security Test
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main]

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create custom rules file
        run: |
          mkdir -p rules
          cat <<'EOF' > rules/custom-rule.yaml
          apiVersion: v1
          kind: O3Rules
          metadata:
            id: node-secrets-exfiltration
            title: Node.js Secrets Exfiltration Detection
            description: Detects a multi-step attack where a node process reads .env and then attempts network egress.
            category: Supply Chain Attack
            severity: critical
          spec:
            severity: critical
            target:
              binary: node
            detection:
              sequence:
                steps:
                  - id: read-secrets
                    file:
                      read:
                        path: [".env"]
                  - id: network-exfil
                    network:
                      connect:
                        direction: outbound
                        scope: external
                        action: block
          EOF

      - name: Run Kayo Security Analysis
        uses: ./ # Use the local action to include our script changes
        with:
          rules: ./rules

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install and run malicious package
        # NOTE: This step requires a 'malicious-npm-package' directory with a package
        # that performs actions matching the rule (reads .env, makes network call).
        run: |
          cd malicious-npm-package
          npm install
          npm start

      - name: Stop Kayo and Check Results
        if: always()
        run: |
          # Wait for any final detections to be logged
          sleep 10

          echo "=== Final Kayo Logs ==="
          docker logs kayo-final-test 2>&1 || echo "No logs available"
          echo ""

          echo "=== Extracting Attack Report ==="
          # Use docker exec without -it (no TTY in GitHub Actions)
          docker exec kayo-final-test cat /app/attack-runtime.json 2>/dev/null || \
            docker exec kayo-final-test ls -la /app/ 2>/dev/null || \
            echo "No attack report file found"
          echo ""

          echo "=== Copying Attack Report to Workspace ==="
          docker cp kayo-final-test:/app/attack-runtime.json ./attack-report.json 2>/dev/null || \
            echo "Could not copy attack report"

          if [ -f ./attack-report.json ]; then
            echo "Attack report saved to: ./attack-report.json"
            cat ./attack-report.json
          fi
          echo ""

          echo "Stopping Kayo container..."
          # The container will be automatically removed on stop because we used --rm
          docker stop kayo-final-test 2>/dev/null || true
          echo "✓ Security monitoring completed"

      - name: Upload Attack Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kayo-attack-report
          path: attack-report.json
          if-no-files-found: warn
